name       : haskell-tar-conduit
version    : 0.3.2
release    : 1
source     :
    - https://hackage.haskell.org/package/tar-conduit-0.3.2/tar-conduit-0.3.2.tar.gz : 004578db7088e7ad53e23f8a293d739314698f0ec421ffad7be101e13c1cf62d
license    : MIT
component  : programming.haskell
summary    : Extract and create tar files using conduit for streaming
description: |
    Extract and create tar files using conduit for streaming
builddeps  :
    - haskell-cabal-install
    - haskell-conduit-devel
    - haskell-conduit-combinators-devel
    - haskell-safe-exceptions-devel
rundeps    :
    - devel:
        - haskell-conduit-devel
        - haskell-conduit-combinators-devel
        - haskell-safe-exceptions-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
